### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by petryeric** [KonstantinGasser/scotty#9]
Hey
I would like to start contributing to this project. Is there anything I should pay attention to or any guidelines or rules?

**Comment by KonstantinGasser** [comment]
Hi 
cool! And thanks for the pointer, I have created [CONTRIBUTING.md](https://github.com/KonstantinGasser/scotty/blob/main/CONTRIBUTING.md). In there is also a note regarding testing locally with the dummy app in the `/test/application` directory. 

In case the guidelines are missing something or are unclear; let me know happy to align them 😄
